version: "3"
services:
  node-app:
    # The node-app service uses an image that’s built from the Dockerfile in the current directory.
    build: .
    image: maerd19/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  # The mongo service uses a public mongo image pulled from the Docker Hub registry.
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ivan
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  # The redis service uses a public Redis image pulled from the Docker Hub registry.
  redis:
    image: redis

volumes:
  mongo-db:
